DEMO_PROJECTS = [
    {
        "id": "pharma-servicedesk",
        "name": "ServiceDesk для фармацевтической сети",
        "client": "Ламода",
        "industry": "Фармацевтика",
        "platform": "ELMA",
        "product": "ServiceDesk",
        "features": [
            {
                "name": "Регистрация и маршрутизация обращений аптечных точек",
                "analysisHours": 32,
                "developmentHours": 96,
                "testingHours": 28,
                "stack": "ELMA BPM, JavaScript, REST API",
            },
            {
                "name": "Интеграция с бухгалтерской учетной системой",
                "analysisHours": 40,
                "developmentHours": 120,
                "testingHours": 36,
                "stack": "C#, REST API, MS SQL",
            },
            {
                "name": "SLA-контроль заявок сервисной поддержки",
                "analysisHours": 24,
                "developmentHours": 72,
                "testingHours": 24,
                "stack": "ELMA BPM, JavaScript",
            },
        ],
    },
    {
        "id": "construction-crm",
        "name": "CRM для строительного холдинга",
        "client": "Технониколь",
        "industry": "Строительство",
        "platform": "Bitrix24",
        "product": "CRM",
        "features": [
            {
                "name": "Воронка продаж объектов недвижимости",
                "analysisHours": 28,
                "developmentHours": 88,
                "testingHours": 24,
                "stack": "PHP, Bitrix24 REST, MySQL",
            },
            {
                "name": "Интеграция CRM с бухгалтерской системой",
                "analysisHours": 36,
                "developmentHours": 112,
                "testingHours": 32,
                "stack": "PHP, 1C API, REST",
            },
            {
                "name": "Аналитические отчеты для руководителя отдела продаж",
                "analysisHours": 30,
                "developmentHours": 80,
                "testingHours": 20,
                "stack": "JavaScript, SQL, BI connector",
            },
        ],
    },
    {
        "id": "refinery-call-center",
        "name": "Колл-центр для нефтеперерабатывающего предприятия",
        "client": "Газпромнефть",
        "industry": "Нефтепереработка",
        "platform": "BPMSoft",
        "product": "Колл-центр",
        "features": [
            {
                "name": "Учет рабочего времени операторов колл-центра",
                "analysisHours": 26,
                "developmentHours": 76,
                "testingHours": 22,
                "stack": "C#, BPMSoft, PostgreSQL",
            },
            {
                "name": "Аналитические отчеты для руководителя колл-центра",
                "analysisHours": 34,
                "developmentHours": 92,
                "testingHours": 26,
                "stack": "C#, SQL, Power BI",
            },
            {
                "name": "Интеграция телефонии с карточкой обращения",
                "analysisHours": 30,
                "developmentHours": 108,
                "testingHours": 34,
                "stack": "C#, SIP, REST API",
            },
        ],
    },
    {
        "id": "bank-bpm",
        "name": "Автоматизация клиентских процессов банка",
        "client": "Газпромнефть",
        "industry": "Финансовые услуги",
        "platform": "ELMA",
        "product": "BPM",
        "features": [
            {
                "name": "Согласование заявок на изменение клиентских лимитов",
                "analysisHours": 44,
                "developmentHours": 132,
                "testingHours": 40,
                "stack": "ELMA BPM, Java, Oracle",
            },
            {
                "name": "Интеграция с системой электронного архива",
                "analysisHours": 30,
                "developmentHours": 86,
                "testingHours": 24,
                "stack": "Java, SOAP, Oracle",
            },
            {
                "name": "Контроль сроков обработки клиентских обращений",
                "analysisHours": 22,
                "developmentHours": 64,
                "testingHours": 20,
                "stack": "ELMA BPM, JavaScript",
            },
        ],
    },
    {
        "id": "retail-helpdesk",
        "name": "HelpDesk для розничной сети",
        "client": "Ламода",
        "industry": "Ритейл",
        "platform": "Bitrix24",
        "product": "ServiceDesk",
        "features": [
            {
                "name": "Классификация обращений магазинов по категориям",
                "analysisHours": 18,
                "developmentHours": 54,
                "testingHours": 16,
                "stack": "PHP, Bitrix24 REST",
            },
            {
                "name": "Учет времени работы сотрудников поддержки",
                "analysisHours": 20,
                "developmentHours": 58,
                "testingHours": 18,
                "stack": "PHP, JavaScript, MySQL",
            },
            {
                "name": "Дашборд качества обслуживания для руководителя",
                "analysisHours": 26,
                "developmentHours": 74,
                "testingHours": 20,
                "stack": "JavaScript, SQL",
            },
        ],
    },
]
